name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.0
          
      - name: Install dependencies
        run: bun install
        
      - name: Type check
        run: bun typecheck
        
      - name: Lint
        run: bun lint
        
      - name: Run tests
        run: bun run test
        
      - name: Build
        run: bun run build
        
      - name: Check build output
        run: |
          if [ ! -d "dist" ]; then
            echo "Build failed: dist directory not found"
            exit 1
          fi
          echo "Build successful: dist directory exists"
          ls -la dist/