# DEPRECATED: This workflow has been replaced by auto-release.yml
# To prevent accidental triggers, this workflow is disabled.
# Delete this file after confirming auto-release.yml works correctly.

name: Publish to npm (DEPRECATED - DO NOT USE)

on:
  workflow_dispatch: # Only manual trigger to prevent accidents
  # push:
  #   tags:
  #     - 'v*' # Disabled to prevent duplicate releases

permissions:
  contents: write # Allow creating releases
  packages: write
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.0
          
      - name: Install dependencies
        run: bun install
        
      - name: Type check
        run: bun typecheck
        
      - name: Lint
        run: bun lint
        
      - name: Build
        run: bun run build

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.0
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: bun install
        
      - name: Build
        run: bun run build
        
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Changes in this Release
            - See [CHANGELOG.md](https://github.com/aniketpanjwani/payload-plugin-email-newsletter/blob/main/CHANGELOG.md) for details
            
            ## Installation
            ```bash
            npm install payload-plugin-newsletter@${{ github.ref_name }}
            ```
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}