# DEPRECATED: This workflow has been replaced by auto-release.yml
# To prevent accidental triggers, this workflow is disabled.
# Delete this file after confirming auto-release.yml works correctly.

name: Release (DEPRECATED - DO NOT USE) to npm

on:
  release:
    types: [published]
  # Also allow manual trigger
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.0

      - name: Install dependencies
        run: bun install

      - name: Run tests (when available)
        run: |
          # Add test command when tests are implemented
          # bun test
          echo "No tests configured yet"

      - name: Type check
        run: bun typecheck

      - name: Build
        run: bun run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}